services:
  db:
    container_name: wissquiz_db
    build:
      context: ./backend/src/main/resources/Database
    environment:
      MYSQL_ROOT_PASSWORD: schnappie
    networks:
      - mynet123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pschnappie"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    container_name: wissquiz_api
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: wissquiz_db
      ENV_VAR: OK
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet123
        
networks:
  mynet123:
    name: mynet123